export const POKEMON_TYPES = {
    fire:     { label: 'fire', icon: '🔥', color: 'bg-orange-500 text-white' },
    water:    { label: 'water', icon: '💧', color: 'bg-blue-500 text-white' },
    grass:    { label: 'grass', icon: '🌿', color: 'bg-green-500 text-white' },
    normal:   { label: 'normal', icon: '⭐', color: 'bg-gray-400 text-white' },
    electric: { label: 'electric',icon: '⚡', color: 'bg-yellow-400 text-black' },
    psychic:  { label: 'psychic',icon: '🔮', color: 'bg-pink-500 text-white' },
    ice:      { label: 'ice', icon: '❄️', color: 'bg-cyan-300 text-black' },
    dragon:   { label: 'dragon', icon: '🐉', color: 'bg-indigo-600 text-white' },
    dark:     { label: 'dark',icon: '🌑', color: 'bg-gray-800 text-white' },
    fairy:    { label: 'fairy', icon: '✨', color: 'bg-pink-300 text-black' },
    fighting: { label: 'fighting',icon: '🥊', color: 'bg-red-700 text-white' },
    poison:   { label: 'poison',icon: '☠️', color: 'bg-purple-500 text-white' },
    ground:   { label: 'ground',icon: '🌍', color: 'bg-yellow-600 text-white' },
    rock:     { label: 'rock',icon: '🪨', color: 'bg-yellow-800 text-white' },
    bug:      { label: 'bug',icon: '🐛', color: 'bg-lime-500 text-white' },
    ghost:    { label: 'ghost', icon: '👻', color: 'bg-purple-800 text-white' },
    steel:    { label: 'steel',icon: '⚙️', color: 'bg-gray-500 text-white' },
    flying:   { label: 'flying',icon: '🦅', color: 'bg-sky-400 text-white' },
}